### ISSUE TITLE
[Self Host] Mystreamers command crashing bot

### ISSUE THREAD

**Issue by MayhemBill** [MAPReiff/M8-Bot#32]
```
/root/M8-Bot/commands/Streaming/myStreamers.js:35
                        var fileCount = files.length
                                              ^

TypeError: Cannot read property 'length' of undefined
    at fs.readdir (/root/M8-Bot/commands/Streaming/myStreamers.js:35:26)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

I get this whenever I run the command, and then the bot crashes.

**Comment by MAPReiff** [comment]
`files` is undefined. Perhaps you are missing streamers in the streamers folders? The command was meant to be run once streamers are added.

**Comment by MayhemBill** [comment]
I tried to add a streamer and I got 
```
 Uncaught Promise Error:
[2019-07-08 13:30:43] TypeError: Cannot read property 'includes' of undefined
[2019-07-08 13:30:43]     at fetch.then.then.then.mixerInfo (/root/M8-Bot/commands/Streaming/addMixer.js:185:31)
[2019-07-08 13:30:43]     at process._tickCallback (internal/process/next_tick.js:68:7)
```
